config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :pages
  resources :templates
  resources :categories, only: [:index, :post, :delete]
  resources :spreadsheets, only: [:new, :create, :update] do
    member do
      get :tabs
      get :range
      get :js
    end
  end    
  root "pages#index" 



  namespace :admin do
    resources :users, only: [:index, :destroy]
    root "users#index"
  end  



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/spreadsheet.rb
class Spreadsheet < ApplicationRecord
  validates_presence_of :spreadsheet_name
end

app/models/template.rb
class Template < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin


  private
  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path 
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

    require 'google/apis/sheets_v4'
    service = Google::Apis::SheetsV4::SheetsService.new
    service.key = 'AIzaSyCw1eTY-S9Xuxqv4AZ_bfHDlxEJ3KsLuig'
    service.authorization = nil
    response1 = service.get_spreadsheet_values("1m4xuNtoujwTySp3sXS2iZ0gsSk8m9d86S_NtReXHi7o", "nav-top!A2:A9")
    @data1 = response1.values
    response2 = service.get_spreadsheet_values("1m4xuNtoujwTySp3sXS2iZ0gsSk8m9d86S_NtReXHi7o", "promotion!A2:C2")
    @data2 = response2.values
    response3 = service.get_spreadsheet_values("1m4xuNtoujwTySp3sXS2iZ0gsSk8m9d86S_NtReXHi7o", "nav-middle!A2:A5")
    @data3 = response3.values
    response4 = service.get_spreadsheet_values("1m4xuNtoujwTySp3sXS2iZ0gsSk8m9d86S_NtReXHi7o", "item!B2:D9")
    @data4 = response4.values
    response5 = service.get_spreadsheet_values("1m4xuNtoujwTySp3sXS2iZ0gsSk8m9d86S_NtReXHi7o", "item!D2" )
    @data5 = response5.values

  end



end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  before_action :authenticate_user!

  def new
    @spreadsheet = Spreadsheet.new
  end

  def create
    @spreadsheet = Spreadsheet.new(spreadsheet_params)
    @spreadsheet.spreadsheet_name =  @spreadsheet.spreadsheet_name.split('/')[5]
    if @spreadsheet.save
      redirect_to tabs_spreadsheet_path(@spreadsheet)
    else
      #add restriction for unvailid url 
      render :new
    end
  end

  def tabs
    set_spreadsheet

    require 'google/apis/sheets_v4'
    service = Google::Apis::SheetsV4::SheetsService.new
    service.key = 'AIzaSyCw1eTY-S9Xuxqv4AZ_bfHDlxEJ3KsLuig'
    service.authorization = nil
    @reponses = service.get_spreadsheet(@spreadsheet.spreadsheet_name)
    @tabs = service.get_spreadsheet(@spreadsheet.spreadsheet_name, fields: "sheets.properties").sheets

  end

  def update
    set_spreadsheet
    if @spreadsheet.update_attributes(spreadsheet_params)
      if @spreadsheet.range_name == nil
        redirect_to range_spreadsheet_path(@spreadsheet)
      else
        redirect_to js_spreadsheet_path(@spreadsheet)
      end 
    end
  end

  def range
    set_spreadsheet


  end

  def js
    @spreadsheet = Spreadsheet.find(params[:id])  
    require 'google/apis/sheets_v4'
    service = Google::Apis::SheetsV4::SheetsService.new
    service.key = 'AIzaSyCw1eTY-S9Xuxqv4AZ_bfHDlxEJ3KsLuig'
    service.authorization = nil
    response = service.get_spreadsheet_values(@spreadsheet.spreadsheet_name, "#{@spreadsheet.tab_name}!#{@spreadsheet.range_name}")
    @data = response.values
    @array = []
 
    j = 1
    while j <  @data.length do
      h = Hash.new()
      k= 0
      for i in @data[0] 
        h[i] = @data[j][k] 
        k += 1
      end
      j += 1  
      @array << h
    end  
      



  end


  private

  def set_spreadsheet
    @spreadsheet = Spreadsheet.find(params[:id])    
  end

  def spreadsheet_params
    params.require(:spreadsheet).permit(:spreadsheet_name, :tab_name, :tab_id, :range_name)
  end


end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spreadsheets_helper.rb
module SpreadsheetsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/admin/users/index.html.erb
<h1>Admin user index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-TW">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cms</title>
    <meta name="description" content="Gogoro 智慧雙輪購車優惠最新資訊！">
    <meta name="google-site-verification" content="sKxuWAkitwdgBRs9t3aDqL_gulJD80AW4st4Y1uVGfE" />

    <meta property="og:type" content="website">
    <meta property="og:title" content="Gogoro - 本月購車優惠總整理">
    <meta property="og:description" content="Gogoro 智慧雙輪購車優惠最新資訊！">
    <meta property="og:image" content="http://promotion.gogoro.com/images/og/creditcard-linkpost.png">
    <meta property="og:url" content="http://promotion.gogoro.com/tw">
    <link rel="canonical" href="http://promotion.gogoro.com/tw">

    <link rel="stylesheet" media="screen" href="/assets/frontend/main-08bb4c87ec09be0081734edeb37027a20fc1cfb37db0ec2897d198833ae192bd.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <nav class="navbar navbar-default cms">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            
            <a class="navbar-brand" href="/spreadsheets/new">CMS</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><a href="/spreadsheets/new">編輯模版</a></li>
                <li><a href="/spreadsheets/new">產出JS包</a></li>
              </ul>
            </div>
        </nav>
    <% end %>
    <div class="nav navbar-nav navbar-right user">
      <% if current_user %>
        <%= link_to 'Hi', class: "my-name" %>
        <%= link_to('登出', destroy_user_session_path, method: :delete) %> |
        <%= link_to('修改密碼', edit_user_registration_path) %>
      <% else %>
        <%= link_to('註冊', new_user_registration_path) %> |
        <%= link_to('登入', new_user_session_path) %>
      <% end %>
    </div>
    <% if notice %>
      <div class="alert remind fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <p><%= notice %></p>
      </div>
    <% elsif alert %>
      <div class="alert remind fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <p><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>

    <% if current_user %>
      
    <% end %>
  
  </body>
</html>

app/views/pages/index.html.erb
<main class="main">
  <div class="hero-container">
    <div class="hero-list">
      <div class="hero hero--left-center">
        <div class="hero-copy-layer" style="color: #ffffff">
          <div class="container h-100">
            <div class="hero-copy-wrapper">

              <div class="hero-copy-inner-wrapper">

                <promotion-img saver_id="1"></promotion-img>
                <!--在這裡-->
                <div class="next-line">
                  <h1 class="hero-copy-title"><promotion-text saver_id="1"></promotion-text></h1>
                </div>
                 <!--在這裡-->
                 <div></div>
                 <div></div>
                  <div></div>
                 <div></div>
                  <div></div>
                 <div></div>
                <div class="hero-copy-description"></div>
                <ip id= ></ip>
                <!--在這裡-->
                  <a class="hero-action-link promotion-btn promotion-primary-btn" href="https://promotion.gogoro.com/tw/gogoro-2-far-eastone/"><promotion-btn saver_id="1"></promotion-btn></a>
                <!--在這裡-->

              </div>
            </div>
          </div>
        </div>
        <div class="hero-background-layer" style="background: #000000;">
          <div class="hero-background hero-background--large" style="background-image: url(/uploads/heroes/3-large-image-ba79916e9a30f9cdb3ee17f3816037183aeb4d2d.jpg?1517814236)"></div>
          <div class="hero-background hero-background--small" style="background-image: url(/uploads/heroes/3-small-image-1cb33a191a0c5005dde6be6f2d9ad30998e4e05a.jpg?1517814237)"></div>
        </div>
      </div>
    </div>
  </div>

  <nav class="gc-nav-against">
    <input type="checkbox" class="navigation-toggle" id="navigation-toggle">
    <div class="navigation-bar">
      <label class="navigation-toggle-close" for="navigation-toggle"></label>
      <div class="container navigation-container">
        <ul class="navigation-list">

          <!--在這裡-->
            <% @data3.each do |data| %>
              <li class="navigation-item navigation-item--active">
                <label class="navigation-toggle-trigger" for="navigation-toggle">
                  <a class="navigation-link" href="/tw/">
                    <span class="navigation-link-text"><%= data[0] %></span>
                  </a>
                </label>
              </li>
            <% end %>
          <!--在這裡-->

          <!--<li class="navigation-modal-bg"></li>-->
        </ul>
      </div>
    </div>
    <div class="navigation-placeholder"></div>
  </nav>

  <div class="container">
    <div class="promotion-list">

      <!--在這裡-->
          <% i = 1 %>
          <% @data4.each do |data| %>
            <a class="promotion-item-link row" href="/tw/gogoro-2-far-eastone">
              <div class="col-lg-6 col-xl-5 col-md-6 promotion-item-cover-photo-column">
                <div class="promotion-item-cover-photo" style="background-image: url(/uploads/promotions/11-cover-photo-62f3a13e91b84c3f51324584d6efccf5c0d5a550.png?1518155967)"></div>
              </div>
              <div class="col-lg-6 col-xl-7 col-md-6 promotion-item-content-column">
                <div class="promotion-item-content">
                  <div>
                    <%= image_tag("/img/" + i.to_s + ".png") %>
                    <div class="promotion-text">
                      <h2 class="promotion-item-name"><%= data[0] %></h2>
                      <div class="promotion-item-description"><div><%= data[1] %></div></div>
                    </div>
                  </div>
                </div>
              </div>
            </a>
            <% i = i + 1 %>
          <% end %>
        <!--在這裡--><abc id=1></abc>

      <div class="text-center">

        <!--在這裡-->
          <a class="promotion-btn promotion-primary-btn" href="http://promotion.gogoro.com/tw/archive"><%= @data5[0][0] %></a>
        <!--在這裡-->

      </div>
    </div>
  </div>
</main>






<script type="text/javascript"> var CLIENT_ID = '673381173216-1cg3p0mqapitdm647sqtn8umspgnncln'; var API_KEY = 'AIzaSyBejq9v2EcnUSjL5aR5CJ2jpOn_NL3oHoA'; var DISCOVERY_DOCS = ["https://sheets.googleapis.com/$discovery/rest?version=v4"]; var SCOPES = "https://www.googleapis.com/auth/spreadsheets.readonly"; function handleClientLoad() { gapi.load('client:auth2', initClient); } function initClient() { gapi.client.init({ apiKey: API_KEY, clientId: CLIENT_ID, discoveryDocs: DISCOVERY_DOCS, scope: SCOPES }).then(function () { putItIn(

'1m4xuNtoujwTySp3sXS2iZ0gsSk8m9d86S_NtReXHi7o',["promotion!A:A", "promotion!B:B", "promotion!C:C"],["promotion-img", "promotion-text", "promotion-btn"], ["2", "1", "1"]

); }); } function putItIn(spreadsheet_id, ranges, tag_name, category) { gapi.client.sheets.spreadsheets.values.batchGet({ spreadsheetId: spreadsheet_id, ranges: ranges, }).then(function(response) { var result = response.result; if (result.valueRanges.length > 0) { for (i = 0; i < result.valueRanges.length; i++) { for (j = 0; j < result.valueRanges[i].values.length; j++) { var row = result.valueRanges[i].values[j]; var tags = document.getElementsByTagName(tag_name[i]); var col_or_row = ranges[i].split(":"); for (k = 0; k < row.length; k++) { var tag_id; Number(col_or_row[1]) ? tag_id = k : tag_id = j; if ( category[i] == "1" ) { l = 0; while(l < tags.length){ if(tags[l].attributes.getNamedItem("saver_id").nodeValue == tag_id){ tags[l].innerHTML = row[k]; } l++; } } else if ( category[i] == "2") { l = 0; while(l < tags.length){ if(tags[l].attributes.getNamedItem("saver_id").nodeValue == tag_id){ var img = document.createElement("img"); tags[l].appendChild(img); tags[l].childNodes[0].src = row[k]; } l++; } } else { l = 0; while(l < tags.length){ if(tags[l].attributes.getNamedItem("saver_id").nodeValue == tag_id){ var iframe = document.createElement("iframe"); tags[l].appendChild(iframe); tags[l].childNodes[0].src = row[k]; } l++; } } } } } } else { document.getElementsByTagName(tag_name[i])[0].innerHTML = 'No data found.'; } }, function(response) { var textnode = document.createTextNode('Error: ' + response.result.error.message); document.getElementsByTagName(tag_name[i])[0].parentNode.appendChild(textnode); }); } </script> <script async defer src="https://apis.google.com/js/api.js" onload="this.onload=function(){};handleClientLoad()" onreadystatechange="if (this.readyState === 'complete') this.onload()"> </script>

app/views/pages/show.html.erb
<h1>Show</h1>
 

app/views/spreadsheets/js.html.erb
<h1>JS</h1>
 
<%= @array  %>


 

app/views/spreadsheets/new.html.erb
<div class="type-id">
  <%= form_for @spreadsheet do |f| %>
    <div class="form-group">
      <%= f.text_field :spreadsheet_name, autofocus: true, placeholder: "Which spreadsheet ?" %>
    </div>
    <%= f.submit 'NEXT' %>
  <% end %>
  <% if @spreadsheet.errors.present? %>
    <ul class="after-rendering"><li><%= @spreadsheet.errors.full_messages.to_sentence%></li></ul>
  <% end %>
</div>

app/views/spreadsheets/range.html.erb
<div class="some-tab">
  <h1>Specify The Range</h1>
    <div class="tab">
      <iframe src=<%="https://docs.google.com/spreadsheets/d/#{@spreadsheet.spreadsheet_name}/edit#gid=#{@spreadsheet.tab_id}" %>></iframe>
    </div>
</div>
<div class="type-range">
  <%= form_for @spreadsheet do |f| %>
    <div class="form-group">
      <%= f.text_field :range_name, autofocus: true, placeholder: "Ex: A1:D5" %>
    </div>
    <%= f.submit 'NEXT' %>
  <% end %>
  <% if @spreadsheet.errors.present? %>
    <ul class="after-rendering"><li><%= @spreadsheet.errors.full_messages.to_sentence%></li></ul>
  <% end %>
</div>
 <div class="back">
  <%= link_to 'back', url_for(:back), class: "btn-back" %>
</div>

app/views/spreadsheets/tabs.html.erb
<div class="all-tabs">
  <h1>TABS</h1>
  <% @tabs.each do |tab| %>   
    <%= link_to spreadsheet_path(@spreadsheet, spreadsheet: {:tab_name => "#{tab.properties.title}", :tab_id => "#{tab.properties.sheet_id}" } ), method: :patch do %>
      <button type="submit" form="form1" value="Submit" class="choice" action= "<% spreadsheet_path(@spreadsheet )%>" method= "put">
        <p><%= tab.properties.title %></p>
          <div class="tab">
            <iframe  src=<%="https://docs.google.com/spreadsheets/d/#{@spreadsheet.spreadsheet_name}/edit#gid=#{tab.properties.sheet_id}"%> ></iframe>
          </div>
      </button> 
    <% end %>
  <% end %>
</div>
<div class="back">
<%= link_to 'back', url_for(:back), class: "btn-back" %>
</div>
 
 